project_id = "eyfphbvexwgigmmyumbm"

[functions.send-notification]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.notify-milestone]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.welcome-email]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
